# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'scheduling' do

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'

end
